services:
  - type: web
    name: securetask-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health/ready
    envVars:
      - key: SECURETASK_DATABASE_URL
        fromDatabase:
          name: securetask-db
          property: connectionString
      - key: SECURETASK_SECRET_KEY
        generateValue: true
      - key: SECURETASK_ALGORITHM
        value: HS256
      - key: SECURETASK_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: SECURETASK_ENVIRONMENT
        value: production
      - key: SECURETASK_DEBUG
        value: "false"

databases:
  - name: securetask-db
    region: frankfurt
    plan: free
    ipAllowList: []
